== The Board
* STM32F103C8T6 aka "Blue Pill"
* Reference manual: https://www.st.com/resource/en/reference_manual/cd00171190.pdf

== Dev Env Overview
* Use FTDI USB to Serial device to upload new programs
* Linux kernel config needed for FTDI USB to Serial (for users with custom kernel):
  - CONFIG_USB_SERIAL
  - CONFIG_USB_SERIAL_FTDI_SIO
* FTDI connection to Blue Pill: Rx connects to pin A10, Tx connects to pint A9
* Running this in a VirtualBox Linux (Gentoo) VM so I pass through the FTDI USB device
* Will use debian docker image for dev env
* Other requirements:
  - STM32 CMSIS libraries for interacting with STM32
  - GCC toolchain for building 
  - STM32 Flasher for uploading programs

=== Official STM32 CMSIS Files
* Download from: http://www.st.com/en/embedded-software/stm32cubef1.html
  - I keep a version of this with only the required files
 
=== GCC Toolchain Install
[source,bash]
-----------------
apt install -y gcc-arm-none-eabi
-----------------

=== STM32 Flasher Install
* Flasher: https://git.code.sf.net/p/stm32flash/code

[source,bash]
-----------------
git clone https://git.code.sf.net/p/stm32flash/code stm32flash-code
cd /tmp/stm32flash-code
make && make install
-----------------

At this point you should be able to use the flasher to dump some information
about the STM32. Put the STM32 in programming mode by moving the BOOT0 jumper
to position 1 and then pressing the reset button.

Now try stm32flash as follows:

[source,bash]
-----------------
# stm32flash /dev/ttyUSB0 # Replace ttyUSB0 with your USB TTY device name
stm32flash 0.5

http://stm32flash.sourceforge.net/

Interface serial_posix: 57600 8E1
Version      : 0x22
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0410 (STM32F10xxx Medium-density)
- RAM        : Up to 20KiB  (512b reserved by bootloader)
- Flash      : Up to 128KiB (size first sector: 4x1024)
- Option RAM : 16b
- System RAM : 2KiB

-----------------

== Building
[source,bash]
-----------------
CMSISDIR=/tmp/STM32Cube_FW_F1_V1.8.0/Drivers/CMSIS
STM32F1xx_DIR=${CMSISDIR}/Device/ST/STM32F1xx/Source/Templates
CFLAGS="-std=c99 -Wall -fno-common -mthumb -mcpu=cortex-m3 -DSTM32F103xB -g"
INCLUDES="-I${CMSISDIR}/Include -I${CMSISDIR}/Device/ST/STM32F1xx/Include"

arm-none-eabi-gcc ${CFLAGS} ${INCLUDES} -c main.c -o main.o
arm-none-eabi-gcc ${CFLAGS} ${INCLUDES} -c ${STM32F1xx_DIR}/system_stm32f1xx.c -o system_stm32f1xx.o
arm-none-eabi-as -mcpu=cortex-m3 -o startup_stm32f103xb.o ${STM32F1xx_DIR}/gcc/startup_stm32f103xb.s
arm-none-eabi-gcc main.o system_stm32f1xx.o startup_stm32f103xb.o -T${STM32F1xx_DIR}/gcc/linker/STM32F103XB_FLASH.ld \
                  -mthumb -mcpu=cortex-m3 --specs=nosys.specs --specs=nano.specs -lc -o main.elf
arm-none-eabi-objcopy -R .stack -O binary main.elf main.bin
-----------------

== Flashing
[source,bash]
-----------------
# stm32flash -w main.bin -v -g 0x0 /dev/ttyUSB0
stm32flash 0.5

http://stm32flash.sourceforge.net/

Using Parser : Raw BINARY
Interface serial_posix: 57600 8E1
Version      : 0x22
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0410 (STM32F10xxx Medium-density)
- RAM        : Up to 20KiB  (512b reserved by bootloader)
- Flash      : Up to 128KiB (size first sector: 4x1024)
- Option RAM : 16b
- System RAM : 2KiB
Write to memory
Erasing memory
Wrote and verified address 0x080007b4 (100.00%) Done.

Starting execution at address 0x08000000... done.

-----------------
